### ISSUE TITLE
source is not sync with Pypi

### ISSUE THREAD

**Issue by soda480** [krbcontext/python-krbcontext#2]
I downloaded krbcontext 0.3.3 from PyPi (https://pypi.python.org/pypi/krbcontext/0.3.3) but I noticed the source code doesn't match what is on the current master branch (different commit). Is what is on master going to be released?

**Comment by tkdchen** [comment]
Yeah, there will be 4.0 release which is in development.

**Comment by tkdchen** [comment]
Latest version of ``0.6`` is pushed to PyPI.
