### ISSUE TITLE
Info about using krbcontext in snakebite-py3

### ISSUE THREAD

**Issue by elukey** [krbcontext/python-krbcontext#32]
Hi!

I am trying to replace https://github.com/elukey/snakebite-py3/blob/master/snakebite/kerberos.py with something python3 compatible, and I found `krbcontext`. I tried to replicate the snakebite's code with your library but didn't get far, is it something possible? 

Thanks in advance!

**Comment by tkdchen** [comment]
Hi @elukey, sorry for late response. I had a quick look at the `kerberos.py` in snakebite-py3. Good to see you have done with gssapi.

**Comment by elukey** [comment]
Np! I was a bit clueless before realizing that the solution with gssapi was super simple. Thanks for the answer anyway! :)
