### ISSUE TITLE
No module 'pwd' on importing krbcontext

### ISSUE THREAD

**Issue by tushar-sharma** [krbcontext/python-krbcontext#33]
Hi 

Simply importing the module: krbcontext on Windows 

`import krbcontext  
`

Gives me the following error. 
 
```
import pwd
ModuleNotFoundError: No module named 'pwd'
```

It seems like `krbcontext\context.py` uses `pwd` module which seems to be available only on Unix , is there a workaround for this on Windows?

**Comment by tkdchen** [comment]
I never tested it on Windows. I have to investigate and figure out a solution or workaround. Does anyone else have some ideas or suggestions? Thanks.

**Comment by tkdchen** [comment]
In addition, Windows wasn't a target platform when this module was created. So, I'm not sure if krbcontext could work well on Windows even if this issue gets fixed.

**Comment by tkdchen** [comment]
Close this issue. Welcome patch to make it work on Windows.
